"""
Bot Command Handlers
Telegram command handlers for the bot
"""
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ContextTypes
from typing import Optional

# Import from core
from bot.core import bot
from strategies.manager import analyze_market

# Default referral link (can be moved to settings)
REFERRAL_LINK = "https://pocket-friends.com/r/ugauihalod"


async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /start command"""
    user = update.effective_user
    bot.add_user(user.id, user.username, user.first_name)
    
    welcome_text = """
👋 Добро пожаловать в Crypto Signals Bot!

Я анализирую рынок и даю торговые сигналы с высокой точностью.

📊 Команды:
• /short - получить SHORT сигнал (1-5 мин)
• /long - получить LONG сигнал (1-4 часа)
• /my_stats - ваша статистика
• /set_bank [сумма] - установить банк
• /set_strategy - выбрать стратегию

🚀 Начните с /short или /long
"""
    
    keyboard = [
        [InlineKeyboardButton("⚡ SHORT", callback_data="get_short_signal")],
        [InlineKeyboardButton("🔵 LONG", callback_data="get_long_signal")],
        [InlineKeyboardButton("📊 Статистика", callback_data="my_stats")]
    ]
    
    await update.message.reply_text(
        welcome_text,
        reply_markup=InlineKeyboardMarkup(keyboard)
    )


async def short_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /short command - get short timeframe signal"""
    user_id = update.effective_user.id
    bot.add_user(user_id, update.effective_user.username, update.effective_user.first_name)

    # Check quota
    if not bot.can_use_signal(user_id, max_free_per_day=3):
        await update.message.reply_text(
            f"📛 Лимит бесплатных сигналов достигнут (3/день).\nЧтобы снять ограничения, зарегистрируйтесь по реферальной ссылке: {REFERRAL_LINK}"
        )
        return

    await update.message.reply_text("⚡ SHORT Signal — генерируется, пожалуйста подождите...")

    # Generate short (fast) signal using statistical/strategy analyzer (placeholder)
    try:
        result = await analyze_market(asset="EURUSD", ticker="EURUSD", timeframe="5M")
        signal = result.get('signal', {}).get('signal', 'neutral') if result else 'neutral'
        confidence = result.get('signal', {}).get('confidence', 0) if result else 0
        price = result.get('signal', {}).get('price', 0) if result else 0

        # Save and increment quota
        bot.save_signal(user_id, asset="EURUSD", timeframe="5M", signal_type="short", entry_price=price, stake_amount=0, confidence=confidence)
        bot.increment_signal_count(user_id)

        await update.message.reply_text(f"⚡ SHORT: {signal.upper()} | Confidence: {confidence}% | Asset: EURUSD")
    except Exception as e:
        await update.message.reply_text("❌ Ошибка при генерации сигнала. Попробуйте позже.")


async def long_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /long command - get long timeframe signal"""
    user_id = update.effective_user.id
    bot.add_user(user_id, update.effective_user.username, update.effective_user.first_name)

    # Check quota
    if not bot.can_use_signal(user_id, max_free_per_day=3):
        await update.message.reply_text(
            f"📛 Лимит бесплатных сигналов достигнут (3/день).\nЧтобы снять ограничения, зарегистрируйтесь по реферальной ссылке: {REFERRAL_LINK}"
        )
        return

    await update.message.reply_text("🔵 LONG Signal — генерируется (OpenRouter), подождите...")

    try:
        # Long signals should be generated by OpenRouter/AI — placeholder uses strategy analyzer
        result = await analyze_market(asset="BTC-USD", ticker="BTC-USD", timeframe="1H")
        signal = result.get('signal', {}).get('signal', 'neutral') if result else 'neutral'
        confidence = result.get('signal', {}).get('confidence', 0) if result else 0
        price = result.get('signal', {}).get('price', 0) if result else 0

        bot.save_signal(user_id, asset="BTC-USD", timeframe="1H", signal_type="long", entry_price=price, stake_amount=0, confidence=confidence)
        bot.increment_signal_count(user_id)

        await update.message.reply_text(f"🔵 LONG: {signal.upper()} | Confidence: {confidence}% | Asset: BTC-USD")
    except Exception as e:
        await update.message.reply_text("❌ Ошибка при генерации LONG сигнала. Попробуйте позже.")


async def my_stats_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /my_stats command"""
    user_id = update.effective_user.id
    
    stats = bot.get_user_stats(user_id)
    balance = bot.get_user_balance(user_id)
    strategy = bot.get_user_strategy(user_id)
    
    text = f"""
📊 Ваша статистика

💰 Банк: {balance:.0f}₽
📈 Стратегия: {strategy}

📊 Всего сделок: {stats['total']}
✅ Wins: {stats['wins']}
❌ Losses: {stats['losses']}
📈 Win Rate: {stats['win_rate']:.1f}%
"""
    
    await update.message.reply_text(text)


async def set_bank_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /set_bank command"""
    user_id = update.effective_user.id
    
    if context.args:
        try:
            balance = float(context.args[0])
            bot.set_user_balance(user_id, balance)
            await update.message.reply_text(f"✅ Банк установлен: {balance}₽")
        except ValueError:
            await update.message.reply_text("❌ Неверная сумма. Используйте: /set_bank 10000")
    else:
        balance = bot.get_user_balance(user_id)
        await update.message.reply_text(f"💰 Текущий банк: {balance}₽\n\nИзменить: /set_bank [сумма]")


async def set_strategy_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /set_strategy command"""
    user_id = update.effective_user.id
    
    current = bot.get_user_strategy(user_id)
    
    text = f"""
🎯 Выбор стратегии

Текущая: {current}

Доступные стратегии:
• martingale - классический мартингейл (x3)
• percentage - процент от депозита (2.5%)
• dalembert - система д'Аламбера
• conservative - консервативная (1%)

Изменить: /set_strategy [название]
"""
    
    keyboard = [
        [InlineKeyboardButton("🎰 Martingale", callback_data="set_strategy_martingale")],
        [InlineKeyboardButton("📈 Percentage", callback_data="set_strategy_percentage")],
        [InlineKeyboardButton("🎲 D'Alembert", callback_data="set_strategy_dalembert")],
        [InlineKeyboardButton("🛡️ Conservative", callback_data="set_strategy_conservative")]
    ]
    
    await update.message.reply_text(
        text,
        reply_markup=InlineKeyboardMarkup(keyboard)
    )


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /help command"""
    text = """
📖 Справка по командам

Основные команды:
• /start - начать работу
• /short - SHORT сигнал (1-5 мин)
• /long - LONG сигнал (1-4 часа)
• /my_stats - статистика
• /set_bank - установить банк
• /set_strategy - выбрать стратегию

Отчеты:
• /report_win - сообщить о выигрыше
• /report_loss - сообщить о проигрыше

Админ:
• /admin_panel - панель админа
"""
    await update.message.reply_text(text)


async def report_win_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /report_win command"""
    user_id = update.effective_user.id
    # Get last signal and update result
    signals = bot.get_user_signals(user_id, 1)
    if signals:
        bot.update_signal_result(signals[0]['id'], 'win')
        await update.message.reply_text("✅ Отмечено как WIN!")
    else:
        await update.message.reply_text("❌ Нет активных сигналов")


async def report_loss_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /report_loss command"""
    user_id = update.effective_user.id
    signals = bot.get_user_signals(user_id, 1)
    if signals:
        bot.update_signal_result(signals[0]['id'], 'loss')
        await update.message.reply_text("✅ Отмечено как LOSS!")
    else:
        await update.message.reply_text("❌ Нет активных сигналов")

async def photo_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle incoming photo (screenshot) from user"""
    user_id = update.effective_user.id
    bot.add_user(user_id, update.effective_user.username, update.effective_user.first_name)

    if not update.message.photo:
        await update.message.reply_text("❌ Нет изображения для анализа")
        return

    # Get highest resolution photo
    photo = update.message.photo[-1]
    file = await context.bot.get_file(photo.file_id)
    img_bytes = await file.download_as_bytearray()

    await update.message.reply_text("🔎 Анализирую скриншот, подождите...")

    analysis = analyze_screenshot(bytes(img_bytes))
    # Save analysis to DB
    try:
        bot.db.save_screenshot_analysis(user_id, analysis)
    except Exception:
        pass

    # Respond with summary
    summary = analysis.get('notes', 'Анализ завершён')
    await update.message.reply_text(f"✅ Анализ завершён:\n{summary}")

# Command list for bot setup
COMMANDS = [
    ("start", "Начать работу с ботом"),
    ("short", "SHORT сигнал"),
    ("long", "LONG сигнал"),
    ("my_stats", "Ваша статистика"),
    ("set_bank", "Установить банк"),
    ("set_strategy", "Выбрать стратегию"),
    ("report_win", "Отчет о выигрыше"),
    ("report_loss", "Отчет о проигрыше"),
    ("help", "Помощь"),
]
